# 错误和异常

通常错误可被分为两种：**语法错误** 和 **异常** 。

Python 中有许多 [内置异常](https://docs.python.org/zh-cn/3.12/library/exceptions.html#bltin-exceptions) ，比如 `NameError` 、 `TypeError` 等。

## 异常的处理

使用 `try` 和 `except` 语句来处理异常。

```python
while True:
    try:
        x = int(input('请输入一个数字：'))
        break
    except ValueError:
        print('您输入的不是数字，请再次尝试输入！')
```

`try` 语句可以有多个 `except` 语句，分别处理不同的异常。也可以在 `except` 语句中使用元组来一同应对多个异常：

```python
except (RuntimeError, TypeError, NameError):
    pass
```

如果发生的异常是 `except` 子句中的异常类的子类，则该 `except` 子句会被触发：

```python
class B(Exception):
    pass

class C(B):
    pass

for cls in [B, C]:
    try:
        raise cls()
    except B:
        print("B")  # 只会触发该句
    except C:
        print("C")
```

`except` 子句可以在异常类后面指定一个变量，该变量会绑定到其异常实例上：

```python
except OSError as err:
    print("OS error: {0}".format(err))
```

异常对象的参数存储在 `args` 属性中。方便起见，`Exception` 类的 `__str__()` 方法会直接输出 `args` 属性的内容：

```python
try:
    raise Exception('spam', 'eggs')
except Exception as inst:
    print(inst.args)    # => ('spam', 'eggs')
    print(inst)         # => ('spam', 'eggs')
```

`BaseException` 是所有异常的共同基类。`Exception` 是它的一个子类，也是所有非致命异常的基类。非 `Exception` 子类的异常通常不被处理（比如 `sys.exit()` 引发的 `SystemExit` 异常），因为他们被用来指示程序应该终止。

`try` 语句还有一个可选的 `else` 子句，它只会在没有异常发生时执行：

```python
for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except OSError:
        print('cannot open', arg)
    else:
        # ...
        f.close()
```

## 触发异常

## 异常链

## 用户自定义异常

## 定义清理操作

## 预定义的清理操作

## 引发和处理多个异常

## 注释异常

可以调用异常对象的 `add_note()` 方法来添加注释，它会在报错时与原报错信息一块显示。

```python
try:
    raise NameError('HiThere')
except NameError as e:
    e.add_note('This is a note.')
    raise
```

## 参考

[错误和异常 - python.org](https://docs.python.org/zh-cn/3.12/tutorial/errors.html)
